pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-u root:root'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
				dir('client') {
					sh 'NODE_ENV=development npm install'
				}
			}
        }
        stage('Test') {
            steps {
				dir('client') {
					sh '../jenkins/scripts/test.sh'
				}
			}
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}

